package com.example.demo.domain.enums;

public enum Genero {

    ACAO, AVENTURA, COMEDIA, DRAMA,
    FICCAO_CIENTIFICA, TERROR, MISTERIO,
    ROMANCE, FANTASIA, DOCUMENTARIO, ANIMACAO,
    MUSICAL, SUSPENSE, CRIME, GUERRA, FAROESTE,
    BIOGRAFIA, HISTORIA, FAMILIA, ANIME, FANTASIA_CIENTIFICA,
    HORROR, THRILLER, ESPIONAGEM, ESPORTE, WESTERN, FILME_NOIR,
    COMEDIA_ROMANTICA, ACAO_E_AVENTURA, FANTASIA_E_AVENTURA,
    DRAMA_ROMANTICO, COMEDIA_DRAMATICA, FANTASIA_CIENTIFICA_E_ACAO,
    ANIMACAO_INFANTIL, FICCAO_HISTORICA, DOCUMENTARIO_CIENTIFICO,
    ROMANCE_HISTORICO, THRILLER_PSICOLOGICO;
}
